### ISSUE TITLE
Support for multiple availability zones in an OpenStack region

### ISSUE THREAD

**Issue by alin2k** [opensecuritycontroller/osc-core#427]
### Description
osc-core\osc-server\src\main\java\org\osc\core\broker\rest\client\openstack\vmidc\notification\runner\OsDeploymentSpecNotificationRunner.java:139:                    // TODO: Future. Openstack. We need to decide should we piggyback on region/zone/name of the AZ.
### Actual Behavior
Based on the TODO comment it looks like it could become a bug  if there are more than one availability zone for a given region.
### Additional Information
Merged DE3918
### Environment
- OSC Version/Build: 
- Cloud Provider Info:
- Plugin Info:
- Other:

### Status
- [ ] Reproduced
- [ ] In Progress
- [ ] Validated     =>    Verified in Version/Build:

**Comment by arvindn05** [comment]
@emanoelxavier Please provide more information on this.

**Comment by emanoelxavier** [comment]
@opensecuritycontroller/osc_triage this originated from a TODO in the code but looking a little deeper this does not seem to surface as functional issue. We are listening to all events related to the region of the DS availability zone instead of just the AZ itself which seems more inclusive. We can probably optimize this further. However I also see from the code that it seems for DS we are listening to events related t host aggregate only, see OsDeploymentSpecNotificationRunner :
```
private OsNotificationObjectType getMemberObjectType(DeploymentSpec ds) {
        // TODO: Future. Openstack. Later add support for Object Type AZ and Host as well.
        return OsNotificationObjectType.HOST_AGGREGRATE;
    }
```
This seems more concerning. @ychoma can you ensure our test cases cover notifications related to DS for AZ, host aggregate etc? If the test cases encounter functional issues related to this we should track those as new issues and address something a bit more targeted.

**Comment by arvindn05** [comment]
@ychoma Please check the notification scenarios for AZ and other ways where we have in creating deployment specs and create issues.

**Comment by ychoma** [comment]
@larkinscarvalho I remember that you made a change to listen to all notifications.     Not sure if your fix is related at all to AZ and host aggregate.

Please let me know.

**Comment by larkinscarvalho** [comment]
@ychoma We still listen to host aggregate events only realted to DS. No changes were made to OsDeploymentSpecNoyifocationRunner.java

**Comment by sudhirappaji** [comment]
@ychoma , could you revert back?

**Comment by ychoma** [comment]
My understanding is that from the code it looks like we are getting notification from AZ only if it's related to DS,  so we will get notifications about our virtual appliances.

For security groups, we don't have the option of grouping by AZ -  only by networks - subnets - and VMs   (The other option is all servers)
It seems like we shouldn't have a problem.  for security groups and for AZ - so should have no problem.

I recommend to close this issue - since we didn't see any real issue with AZ

**Comment by sudhirappaji** [comment]
@ychoma , is this been validated with DS with multiple AZ for a given region?
